### ISSUE TITLE
Extension interferes with Desktop Cube

### ISSUE THREAD

**Issue by FelixFourcolor** [neuromorph/glass_grid#4]
[Desktop Cube](https://github.com/Schneegans/Desktop-Cube) has a feature that allows you to click and drag the desktop or the panel to switch workspaces (i.e. to "rotate the cube"). When this extension is enabled, that feature doesn't work.

(With Desktop Cube you can also click and drag the overview to switch workspaces; that still works with this extension.)

------------------
Gnome 45

**Comment by neuromorph** [comment]
This should not happen as I don't see a conflict with that extension. Frankly, I hadn't used Desktop Cube, so I just installed and tried it on my laptop with Gnome <45 and then also in VM with Gnome 45 and it works in both cases. Here is a cast from the VM running Gnome 45, I hope this is what you are referring to. I first do it with panel and then with desktop but the mouse pointer was not captured in recording. Also, if the Glass Grid panel is open then while Cube still works, the Glass grid panel will not move as it is not part of any workspace, it is like the Top bar panel for e.g.

[Screencast from 11-11-23 03:50:57 PM IST.webm](https://github.com/neuromorph/glass_grid/assets/4656768/ecdd5479-6ddc-4378-8d63-bea97229a76a)

**Comment by FelixFourcolor** [comment]
I see what's going on.

(I can't capture mouse clicks on-video, but you get the point when my mouse moves back and forth.)

https://github.com/neuromorph/glass_grid/assets/34260584/5c4d181c-6519-4a1b-9694-056239fca08a

The extension only interferes with Desktop Cube when you do horizontal movements. Seems like it interprets all horizontal click-n-drags as you trying to scroll the glass panel, even if you don't click on the panel itself. Meanwhile vertical click-n-drags are untouched, so Desktop Cube still works.

When I wrote the issue I happened to only test horizontal movements, while you only tested vetical movements. So there's a miscommunication :)

**Comment by neuromorph** [comment]
Ah, I wasn't aware that Desktop Cube works with horizontal swipes. I tested it now and yes, I can reproduce your issue. 
It is still unclear and a bit weird that it happens. I glanced through Desktop Cube code and got an idea of where the issue could be and so I tried a few things and am able to isolate it to the Swipe tracker. Cube alters Gnome's swipe tracker from Overview to make it work on desktop while I create a new swipe tracker for the scrolling widget only so should not interfere but it does.
Anyway, I plan to disable it when the glass panel is not open so that Cube will work. On the other hand Grid will take over when it is open which makes sense.
I will update here once I have it ready and will also add the fix for the artifact issue.

**Comment by FelixFourcolor** [comment]
Thank you!

**Comment by neuromorph** [comment]
Hello Felix,

I have a release with fixes ready for test. Updates:

- Desktop Cube swipes should work now (except, when Glass Grid is open horizontal swipe will scroll the grid)
- Blur my Shell will not have artifacts. Note: As usual, you need to set 'hack level' in Blur my shell to High quality or up.
- Some update to fonts scaling and Page Swipe pop up.

Release [available here](https://github.com/neuromorph/glass_grid/releases/download/g45-port-extensions-conflicts/extgrid@neuromorph.zip). You will need to follow same steps as before for local install. 
Let me know how it goes.

**Comment by FelixFourcolor** [comment]
Both fixes work. Thank you so much!
